### ISSUE TITLE
Edit Form - Images

### ISSUE THREAD

**Issue by Dimitvp** [mdamyanova/Meow#1]
The form for editing Cats isn't working good with images. Check it.

*Give me more details on this problem. It seems that it is working fine for me.

**Comment by mdamyanova** [comment]
In the Editing Form of the Cats the Image field is only for uploading new Image. We can change that to - 
showing the current Image of the Cat, options for Upload New Image or Delete current image and replace it with the default image programmable. This is an advance thing, we would continue without that. :)

**Comment by Dimitvp** [comment]
I see now. Yes it is tricky business but i think we can do it after we solve the other more important problems. I had similar problems with my app, I could look there for inspiration.

**Comment by mdamyanova** [comment]
We have one mission so far - Don't break anything that's not already broken. 😃

**Comment by mdamyanova** [comment]
As we don't have much time, I suggest to make profile pictures not required and if on edit form we don't upload a photo, the original one stays. :)
