### ISSUE TITLE
Could you remove the Footer and make the site working as it was?

### ISSUE THREAD

**Issue by mdamyanova** [mdamyanova/Meow#2]
Why?

We broke what was working. Especially **listing ICatRescue Cats**. Lets not create yourselves more work to fix things, because we don't have timeeee :) (and we have more important things to consider).
The idea is cool, but **we need to fix the whole design of the project if we start with this footer**. We don't have time for that. Maybe **little fix like using Bootstrap, make it more beautiful what's already here**.

For example, the Details, Adoption and Profile Forms could be made better (psst - they're all the same).

**Comment by Dimitvp** [comment]
I don`t see how the listing of ICarRescue Cats is broken. I commented the footer and the listing looks exactly the same.
