### ISSUE TITLE
Default Image on Profiles

### ISSUE THREAD

**Issue by Dimitvp** [mdamyanova/Meow#3]
Add Default Image on Users Profiles. Problem can occur in ApplicationBuilderExtensions class when we register the Roles.
Also check the Seeder and the Views.

**Comment by Dimitvp** [comment]
Can you give me a little bit more info on this problem?

**Comment by mdamyanova** [comment]
Yes, I think it's all working.
Profile Picture is Required for Registration. Maybe we should fix that and if we don't have a picture to register the User (and Cat) with Default Picture. I think we should write code in the [AccountController](https://github.com/mdamyanova/Meow/blob/91090d50a2ee953c416be6b56381797f540f3b72/Meow/Meow.Web/Controllers/AccountController.cs#L215) and [AdoptionCatService](https://github.com/mdamyanova/Meow/blob/91090d50a2ee953c416be6b56381797f540f3b72/Meow/Meow.Services/Volunteer/Implementations/AdoptionCatService.cs#L25).

**Comment by mdamyanova** [comment]
Done! Users can register without profile picture but cats need to have one.
