### ISSUE TITLE
Location Validation Attribute

### ISSUE THREAD

**Issue by Dimitvp** [mdamyanova/Meow#4]
I wrote by myself all towns in Bulgaria. :D We need to validate the Location if we have time.

**Comment by Dimitvp** [comment]
What is the idea here because i haven`t that before(getting all the cities as attribute, i mean) where we going to get them from?

**Comment by mdamyanova** [comment]
[Towns](https://github.com/mdamyanova/Meow/blob/master/Meow/Meow.Data/Models/Enums/Towns.cs)
[Validation Attribute](https://github.com/mdamyanova/Meow/blob/master/Meow/Meow.Data/Validation/LocationAttribute.cs)
