### ISSUE TITLE
Partial Views

### ISSUE THREAD

**Issue by Dimitvp** [mdamyanova/Meow#5]
What is the perpos for the HTML tags Spam with class=label. If it is not important we can remove them. If we want them I think this is the solution:
https://www.tutorialspoint.com/bootstrap/bootstrap_labels.htm

**Comment by Dimitvp** [comment]
The footer is broken again. I don`t know why.

**Comment by Dimitvp** [comment]
I notice that we are loading css files in the Body tag for each different view that is why i am adding @mdamyanova  to this issue. 
I think that this is very bad  practice. Usually most(if not all of it) of the custom css is written in one file and it is loaded in the Head tag.
I think we should change that. It is also responsible for a lot of the design problems that we are having.

**Comment by mdamyanova** [comment]
Ok. We need a partial view, right?
