### ISSUE TITLE
User adopted cats bug

### ISSUE THREAD

**Issue by ddxkalin** [mdamyanova/Meow#9]
When user adopt a cat, and he enter in his account he sees the home cats/adopt cats menu, but if you're adopted a kitty, when you click on the photo, its 404.

**Comment by mdamyanova** [comment]
Yes, [I know](https://github.com/mdamyanova/Meow/issues/8). We need to fix that. It can be something with the routing and areas? If not - debugging. 😄

**Comment by mdamyanova** [comment]
Fixed it. Look carefully for the areas changes Dimitur made.
